version: 2.1
orbs:
  python: circleci/python@2
jobs:
  test-python:
    docker:
      - image: cimg/python:3.8-node
    working_directory: ~/project/web_app_project/project_board
    steps:
      - checkout:
          path: ~/project
      - python/install-packages
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t my-python-app:latest .
      - run:
          name: Run container in background
          command: |
            docker run -d -p 8000:8000 --name test-app my-python-app:latest
      - run:
          name: Wait for service to start
          command: |
            for i in {1..10}; do
              if curl --fail http://localhost:8000; then
                echo "Service is up!" && exit 0
              fi
              echo "Waiting for service..."
              sleep 3
            done
            echo "Service did not start in time" && exit 1
      - run:
          name: Run tests
          command: pytest --junitxml=junit.xml || ((($? == 5)) && echo 'Did not find any tests to run.')
      - store_test_results:
          path: junit.xml
workflows:
  test-container:
    jobs:
      - test-python
