version: 2.1
jobs:
  test-flask:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run Docker image
          command: |
            docker run -d --name weather-app -p 8000:8000 my-python-app:latest
            sleep 10
            docker ps -a
      - run:
          name: Curl container
          command: |
            curl http://localhost:8000 || (docker logs weather-app && exit 1)
      - run:
          name: Cleanup Docker container
          command: |
            docker stop weather-app || true
            docker rm weather-app || true
workflows:
  version: 2
  test-flask-app:
    jobs:
      - test-flask